blank_issues_enabled: false
contact_links:
  - name: Discussões da Comunidade
    url: https://github.com/orgs/studiopomar/discussions
    about: Faça perguntas, compartilhe suas músicas ou discuta ideias com a comunidade do Studio Pomar.
